"""Memory models for HungerLoop v0.5a.

:class:`MemoryCandidate` is the pre-promotion record generated by
:class:`MemoryManager` from a validated loop. v0.5c will expose CLI to
approve / reject; v0.5a only persists and queries (PRD §19.1).

Promotion predicates (``action_verified``, ``reusable``, ``non_volatile``,
``traceable``) are stored as Boolean fields so the MVP doesn't have to
re-evaluate them at query time.
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

MemoryType = Literal["fact", "procedure", "preference", "pitfall"]
MemoryStatus = Literal["candidate", "approved", "rejected"]


class MemoryCandidate(BaseModel):
    """A proposed memory item awaiting human review."""

    candidate_id: str
    task_id: str
    content: str
    memory_type: MemoryType = "fact"

    evidence_ids: list[str] = Field(default_factory=list)
    referenced_check_keys: list[str] = Field(default_factory=list)
    source_loop_ids: list[int] = Field(default_factory=list)

    # Promotion predicates (PRD §19.2)
    action_verified: bool = False
    reusable: bool = False
    non_volatile: bool = False
    traceable: bool = False

    confidence: float = 0.0
    status: MemoryStatus = "candidate"
