"""Memory models for HungerLoop v0.5a / v0.5c.

:class:`MemoryCandidate` is the pre-promotion record generated by
:class:`MemoryManager` from a validated loop. v0.5c persists the
forward-compat lifecycle fields (PRD §19.1) so v0.6 promotion can be a
pure read-and-flip without a breaking schema migration.

Promotion predicates (``action_verified``, ``reusable``, ``non_volatile``,
``traceable``) are stored as Boolean fields so the MVP doesn't have to
re-evaluate them at query time.
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

MemoryType = Literal["fact", "procedure", "preference", "pitfall"]
MemoryStatus = Literal["candidate", "approved", "rejected"]
MemoryState = Literal[
    "proposed", "approved", "rejected", "expired", "superseded"
]
MemoryDecidedBy = Literal["human", "auto"]


class MemoryCandidate(BaseModel):
    """A proposed memory item awaiting human review."""

    candidate_id: str
    task_id: str
    content: str
    memory_type: MemoryType = "fact"

    evidence_ids: list[str] = Field(default_factory=list)
    referenced_check_keys: list[str] = Field(default_factory=list)
    source_loop_ids: list[int] = Field(default_factory=list)

    # Promotion predicates (PRD §19.2)
    action_verified: bool = False
    reusable: bool = False
    non_volatile: bool = False
    traceable: bool = False

    confidence: float = 0.0
    status: MemoryStatus = "candidate"

    # ----- v0.5c.0 lifecycle fields (PRD §19.1) -------------------------
    # Only ``state="proposed"`` is written in v0.5c; the other values are
    # reserved for v0.6 promotion. Forward-compat now means v0.6 doesn't
    # need a breaking schema migration to act on existing rows.
    state: MemoryState = "proposed"
    decision_loop_id: int | None = None
    decided_by: MemoryDecidedBy | None = None
    decision_rationale: str = ""
    replaces_candidate_id: str | None = None
    expires_at: datetime | None = None
