"""Memory models for HungerLoop v0.5a / v0.5c.

:class:`MemoryCandidate` is the pre-promotion record generated by
:class:`MemoryManager` from a validated loop. v0.5c persists the
forward-compat lifecycle fields (PRD §19.1) so v0.6 promotion can be a
pure read-and-flip without a breaking schema migration.

Promotion predicates (``action_verified``, ``reusable``, ``non_volatile``,
``traceable``) are stored as Boolean fields so the MVP doesn't have to
re-evaluate them at query time.
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

MemoryType = Literal[
    "fact",
    "procedure",
    "preference",
    "pitfall",
    "failure_pattern",
    "tool_usage",
    "workflow_pattern",
]
MemoryStatus = Literal["candidate", "approved", "rejected"]
MemoryState = Literal[
    "proposed", "approved", "rejected", "expired", "superseded", "deferred"
]
MemoryDecidedBy = Literal["human", "auto"]


class MemoryCandidate(BaseModel):
    """A proposed memory item awaiting human review."""

    candidate_id: str
    task_id: str
    content: str
    memory_type: MemoryType = "fact"

    evidence_ids: list[str] = Field(default_factory=list)
    referenced_check_keys: list[str] = Field(default_factory=list)
    accepted_check_keys: list[str] = Field(default_factory=list)
    """v0.5e.0 (PRD §19 / FR-1): the strict subset of
    ``referenced_check_keys`` that *passed* validation. The
    ``ApprovalEngine`` uses this to gate promotion: a candidate
    referencing five checks but only proven on two of them must be
    approved against ``accepted_check_keys``, never the loose
    referenced list."""

    source_loop_ids: list[int] = Field(default_factory=list)
    source_candidate_state_id: str | None = None
    source_validation_id: str | None = None
    source_best_state_id: str | None = None

    # Promotion predicates (PRD §19.2)
    action_verified: bool = False
    reusable: bool = False
    non_volatile: bool = False
    traceable: bool = False

    confidence: float = 0.0
    status: MemoryStatus = "candidate"

    # ----- v0.5c.0 lifecycle fields (PRD §19.1) -------------------------
    # Only ``state="proposed"`` is written in v0.5c; the other values are
    # reserved for v0.6 promotion. Forward-compat now means v0.6 doesn't
    # need a breaking schema migration to act on existing rows.
    state: MemoryState = "proposed"
    decision_loop_id: int | None = None
    decided_by: MemoryDecidedBy | None = None
    decision_rationale: str = ""
    replaces_candidate_id: str | None = None
    expires_at: datetime | None = None

    # ----- v0.5e.0 reviewer audit (PRD §19 / FR-1) ---------------------
    reviewer: str | None = None
    """Operator id (or ``"auto"``) that approved/rejected/deferred the
    row. Populated by the CLI commands; ``None`` for shipped
    proposed-only rows."""

    reviewed_at: datetime | None = None
    """UTC timestamp of the review action; ``None`` until reviewed."""

    rejection_reason: str | None = None
    """Free-text reason recorded by ``memory reject``. ``None`` for
    approved or still-pending rows."""


class PromotedMemory(BaseModel):
    """Persisted promotion record (PRD §19 / FR-21).

    Written by ``ApprovalEngine`` after a :class:`MemoryCandidate` is
    approved and the predicate set evaluates to True. The candidate
    row stays in ``memory_candidates`` (state=``"approved"``); the
    PromotedMemory is the durable artefact returned to operators.
    """

    memory_id: str
    source_candidate_id: str
    task_id: str
    content: str
    memory_type: MemoryType = "fact"
    layer: Literal["task", "global"] = "task"
    """``"task"`` memories ride along with the originating task;
    ``"global"`` memories cross tasks. v0.5e.0 only writes ``"task"``
    by default; ``--layer global`` is reserved for v0.6+."""

    evidence_ids: list[str] = Field(default_factory=list)
    accepted_check_keys: list[str] = Field(default_factory=list)
    reuse_scenarios: list[str] = Field(default_factory=list)
    """Operator-supplied (or auto-extracted) scenarios in which this
    memory should be retrieved. v0.5e.0 stores them but the retrieval
    side lands in v0.6."""

    confidence: float = 0.0
    created_at: datetime
    approved_by: str
