from __future__ import annotations

from typing import Any, Protocol

from hungerloop.models.blackboard import BestState, CandidateState
from hungerloop.models.hunger import (
    HungerClockState,
    HungerItem,
    HungerLedger,
    HungerPolicy,
    HungerSnapshot,
)
from hungerloop.models.enums import LoopPhase
from hungerloop.models.validation import ValidationReport


class RepositoryProtocol(Protocol):
    def get_best_state(self, task_id: str) -> BestState | None: ...
    def save_best_state(self, best: BestState) -> None: ...

    def get_hunger_items(self, item_ids: list[str]) -> list[HungerItem]: ...
    def get_hunger_item(self, item_id: str) -> HungerItem | None: ...
    def save_hunger_item(self, item: HungerItem) -> None: ...
    def get_items_for_check_keys(
        self, task_id: str, check_keys: list[str]
    ) -> list[HungerItem]: ...

    def get_hunger_policy(self, task_id: str) -> HungerPolicy: ...
    def get_hunger_clock(self, task_id: str) -> HungerClockState: ...
    def save_hunger_clock(self, clock: HungerClockState) -> None: ...
    def get_hunger_ledger(self, task_id: str) -> HungerLedger: ...
    def get_last_phase(self, task_id: str) -> LoopPhase | None: ...

    def save_hunger_snapshot(self, task_id: str, snapshot: HungerSnapshot) -> None: ...

    def save_candidate(self, candidate: CandidateState) -> None: ...
    def mark_candidate_committed(self, candidate_id: str) -> None: ...
    def mark_candidate_rejected(self, candidate_id: str) -> None: ...

    def save_validation_report(self, report: ValidationReport) -> None: ...
    def add_failure_from_validation(self, report: ValidationReport) -> None: ...

    def count_evidence_by_type(
        self, task_id: str, evidence_ids: list[str], evidence_type: str
    ) -> int: ...
    def get_artifacts_by_ids(self, artifact_ids: list[str]) -> list[Any]: ...
    def is_approval_granted(self, approval_id: str) -> bool: ...

    def save_shell_output_as_evidence(
        self,
        task_id: str,
        loop_id: int,
        label: str,
        argv: list[str],
        cwd: str,
        exit_code: int,
        stdout: str,
        stderr: str,
        timed_out: bool,
    ) -> str: ...

    def reset_no_progress_streak(self, task_id: str) -> None: ...
    def increment_no_progress_streak(self, task_id: str) -> int: ...

    def next_loop_id(self, task_id: str) -> int: ...

    def append_event(self, event_type: str, payload: dict[str, object]) -> None: ...
